import { RoomId } from '../../../ecs/components/singletons.js';
import type { RoomData } from '../types.js';

/** Shorthand for ironrath prop model path */
const P = (name: string) => `assets/models/props/ironrath/${name}.glb`;

/**
 * Ironrath Castle — Great Hall
 *
 * Generated by Room Needs Engine.
 * 153 prop instances, 11 lights, 12 particle emitters.
 */
const greatHall: RoomData = {
  id: RoomId.IronrathGreatHall,
  name: 'Great Hall',
  dimensions: { width: 24, depth: 14, height: 10 },
  mood: 'grand',

  floorTexture: { basePath: 'assets/textures/stone/northern-floor' },
  wallTexture: { basePath: 'assets/textures/stone/northern-wall' },
  ceilingTexture: { basePath: 'assets/textures/wood/ironwood-ceiling' },

  ambientLight: { color: 0x887766, intensity: 0.85 },

  lights: [
    { type: 'directional', position: { x: 10, y: 8, z: -2 }, color: 0xB0C4DE, intensity: 2, castShadow: true },
    { type: 'point', position: { x: 0, y: 3, z: -6.5 }, color: 0xFF6735, intensity: 10, distance: 14, decay: 1, flicker: true },
    { type: 'point', position: { x: 0, y: 8.5, z: -3 }, color: 0xFFCC66, intensity: 5, distance: 14, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: 0, y: 8.5, z: 0 }, color: 0xFFCC66, intensity: 5, distance: 14, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: 0, y: 8.5, z: 3 }, color: 0xFFCC66, intensity: 5, distance: 14, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: -11.8, y: 4, z: -4 }, color: 0xFFCC66, intensity: 4, distance: 12, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: -11.8, y: 4, z: 3 }, color: 0xFFCC66, intensity: 4, distance: 12, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: 11.8, y: 4, z: -4 }, color: 0xFFCC66, intensity: 4, distance: 12, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: 11.8, y: 4, z: 3 }, color: 0xFFCC66, intensity: 4, distance: 12, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: -4, y: 0, z: -5 }, color: 0xFF6735, intensity: 5, distance: 12, decay: 1, flicker: true }, // iron-brazier
    { type: 'point', position: { x: 4, y: 0, z: -5 }, color: 0xFF6735, intensity: 5, distance: 12, decay: 1, flicker: true }, // iron-brazier
  ],

  doors: [
    {
      position: { x: -12, y: 0, z: 0 },
      halfExtents: { x: 0.8, z: 1.5 },
      targetRoomId: RoomId.IronrathGreatHall, // placeholder — update with actual target
      spawnPoint: { x: 0, y: 0, z: 0 },
      wall: 'west',
    },
  ],

  npcs: [],

  particles: [
    { type: 'dust', region: { minX: -10, maxX: 10, minY: 1, maxY: 8, minZ: -6, maxZ: 5 }, count: 100 },
    { type: 'embers', position: { x: 0, y: 3, z: -6.5 }, count: 30 },
    { type: 'smoke', position: { x: 0, y: 4, z: -6.5 }, count: 25 },
    { type: 'embers', position: { x: 0, y: 8.5, z: -3 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: 0, y: 8.5, z: 0 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: 0, y: 8.5, z: 3 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: -11.8, y: 4, z: -4 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: -11.8, y: 4, z: 3 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: 11.8, y: 4, z: -4 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: 11.8, y: 4, z: 3 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: -4, y: 0, z: -5 }, count: 12 }, // iron-brazier
    { type: 'embers', position: { x: 4, y: 0, z: -5 }, count: 12 }, // iron-brazier
  ],

  props: [
    // ─── STRUCTURAL ─────────────────────────────────────────────
    { // Ironwood pillars flanking the central hall — Forrester si...
      type: 'model', modelPath: P('ironwood-column'), scale: 1,
      positions: [
        { x: -5, y: 0, z: -4 }, { x: -5, y: 0, z: 0 }, { x: -5, y: 0, z: 4 },
        { x: 5, y: 0, z: -4 }, { x: 5, y: 0, z: 0 }, { x: 5, y: 0, z: 4 },
        { x: -8, y: 0, z: 5.5 }, { x: 8, y: 0, z: 5.5 },
      ],
    },
    { type: 'model', modelPath: P('stone-hearth'), positions: [{ x: 0, y: 0.005, z: -6.8 }], scale: 1.2 }, // Great stone hearth dominating the north wall — the heart ...
    { type: 'model', modelPath: P('raised-dais'), positions: [{ x: 0, y: 0.005, z: -5.5 }], scale: 1 }, // Stone platform elevating the lord's seat above the hall —...
    { // Load-bearing stone arches — flanking the hearth and frami...
      type: 'model', modelPath: P('stone-arch'), scale: 1,
      positions: [
        { x: -4.5, y: 0, z: -6.9 }, { x: 4.5, y: 0, z: -6.9 }, { x: 0, y: 0, z: 6.9, rotationY: 3.142 },
      ],
    },
    { // Wall-engaged half-columns articulating the east and west ...
      type: 'model', modelPath: P('stone-pilaster'), scale: 1,
      positions: [
        { x: -11.9, y: 0, z: -5 }, { x: -11.9, y: 0, z: -1 }, { x: -11.9, y: 0, z: 3 },
        { x: 11.9, y: 0, z: -5, rotationY: 3.142 }, { x: 11.9, y: 0, z: -1, rotationY: 3.142 }, { x: 11.9, y: 0, z: 3, rotationY: 3.142 },
      ],
    },
    { // Stone corbels supporting roof beams at the wall junction ...
      type: 'model', modelPath: P('corbel-bracket'), scale: 0.8,
      positions: [
        { x: -11.8, y: 8.5, z: -4 }, { x: -11.8, y: 8.5, z: 0 }, { x: -11.8, y: 8.5, z: 4 },
        { x: 11.8, y: 8.5, z: -4 }, { x: 11.8, y: 8.5, z: 0 }, { x: 11.8, y: 8.5, z: 4 },
      ],
    },
    { type: 'model', modelPath: P('stone-window-frame'), positions: [{ x: 11.9, y: 3, z: -2, rotationY: -1.571 }], scale: 1 }, // Narrow window slit with stone surround on east wall — pro...
    { type: 'model', modelPath: P('door-frame'), positions: [{ x: -11.9, y: 0, z: 0, rotationY: 1.571 }], scale: 1 }, // Heavy stone door frame on the west wall — connects to the...
    { // Main ironwood roof beams spanning the full hall width — m...
      type: 'model', modelPath: P('roof-beam'), scale: 1,
      positions: [
        { x: 0, y: 9.2, z: -4 }, { x: 0, y: 9.2, z: 0 }, { x: 0, y: 9.2, z: 4 },
      ],
    },
    { // Cross joists spanning between main beams — secondary stru...
      type: 'model', modelPath: P('roof-joist'), scale: 1,
      positions: [
        { x: -4, y: 9.5, z: -2, rotationY: 1.571 }, { x: 4, y: 9.5, z: -2, rotationY: 1.571 }, { x: -4, y: 9.5, z: 2, rotationY: 1.571 },
        { x: 4, y: 9.5, z: 2, rotationY: 1.571 },
      ],
    },
    { // Visible rafter sets at the north and south ends — exposed...
      type: 'model', modelPath: P('rafter-set'), scale: 0.8,
      positions: [
        { x: 0, y: 9, z: -6 }, { x: 0, y: 9, z: 6 },
      ],
    },
    // ─── FURNITURE ──────────────────────────────────────────────
    { type: 'model', modelPath: P('ironwood-throne'), positions: [{ x: 0, y: 0.3, z: -5.8 }], scale: 1 }, // The lord's ironwood throne — carved from a single ironwoo...
    { // High seats flanking the throne — reserved for the lord's ...
      type: 'model', modelPath: P('high-seat'), scale: 0.9,
      positions: [
        { x: -2.5, y: 0.3, z: -5.5, rotationY: 0.15 },
        { x: 2.5, y: 0.3, z: -5.5, rotationY: -0.15 },
      ],
    },
    { type: 'model', modelPath: P('long-table'), positions: [{ x: 0, y: 0.005, z: 0 }], scale: 1 }, // Great feasting table — center of social life, where the h...
    { // Ironwood benches flanking the feasting table — seating fo...
      type: 'model', modelPath: P('bench'), scale: 1,
      positions: [
        { x: -2.5, y: 0, z: -1.5 }, { x: -2.5, y: 0, z: 0 }, { x: -2.5, y: 0, z: 1.5 },
        { x: 2.5, y: 0, z: -1.5, rotationY: 3.142 }, { x: 2.5, y: 0, z: 0, rotationY: 3.142 }, { x: 2.5, y: 0, z: 1.5, rotationY: 3.142 },
      ],
    },
    { // Chairs at the table ends — reserved for the steward and c...
      type: 'model', modelPath: P('chair'), scale: 0.9,
      positions: [
        { x: 0, y: 0, z: -2.5, rotationY: 3.142 }, { x: 0, y: 0, z: 2.5 },
      ],
    },
    { // Serving tables against east and west walls near the dais ...
      type: 'model', modelPath: P('sideboard'), scale: 0.9,
      positions: [
        { x: -10, y: 0, z: -5 }, { x: 10, y: 0, z: -5, rotationY: 3.142 },
      ],
    },
    { // Stools scattered along the walls — overflow seating for l...
      type: 'model', modelPath: P('stool'), scale: 0.8,
      positions: [
        { x: -9, y: 0, z: -3 }, { x: 9, y: 0, z: -3 }, { x: -8, y: 0, z: 2 },
        { x: 8, y: 0, z: 2 },
      ],
    },
    { // Weapon racks near the south wall — household arms kept re...
      type: 'model', modelPath: P('weapon-rack'), scale: 0.9,
      positions: [
        { x: -11.5, y: 0, z: 5 }, { x: 11.5, y: 0, z: 5 },
      ],
    },
    { // Iron-bound wooden storage chests — for linens, spare tabl...
      type: 'model', modelPath: P('wooden-chest-large'), scale: 0.9,
      positions: [
        { x: 9, y: 0, z: -5, rotationY: -0.3 }, { x: 10, y: 0, z: 6, rotationY: 0.5 },
      ],
    },
    // ─── LIGHTING FIXTURES ──────────────────────────────────────
    { // Three iron chandeliers along the central axis — the prima...
      type: 'model', modelPath: P('iron-chandelier'), scale: 1,
      positions: [
        { x: 0, y: 8.5, z: -3 }, { x: 0, y: 8.5, z: 0 }, { x: 0, y: 8.5, z: 3 },
      ],
    },
    { // Iron wall sconces for torches — 4 total, 2 per wall, prim...
      type: 'model', modelPath: P('wall-sconce'), scale: 0.5,
      positions: [
        { x: -11.8, y: 4, z: -4 }, { x: -11.8, y: 4, z: 3 }, { x: 11.8, y: 4, z: -4 },
        { x: 11.8, y: 4, z: 3 },
      ],
    },
    { // Iron torch holders mounted below each wall sconce — funct...
      type: 'model', modelPath: P('iron-torch-holder'), scale: 0.6,
      positions: [
        { x: -11.8, y: 3.8, z: -4 }, { x: -11.8, y: 3.8, z: 3 }, { x: 11.8, y: 3.8, z: -4, rotationY: 3.142 },
        { x: 11.8, y: 3.8, z: 3, rotationY: 3.142 },
      ],
    },
    { // Standing iron braziers flanking the dais — provide warmth...
      type: 'model', modelPath: P('iron-brazier'), scale: 0.9,
      positions: [
        { x: -4, y: 0, z: -5 }, { x: 4, y: 0, z: -5 },
      ],
    },
    { // Iron candle trees flanking the throne — tall standing can...
      type: 'model', modelPath: P('iron-candle-tree'), scale: 0.8,
      positions: [
        { x: -1.2, y: 0.3, z: -5.8 }, { x: 1.2, y: 0.3, z: -5.8 },
      ],
    },
    // ─── WALL DECOR ─────────────────────────────────────────────
    { // Forrester house banners — the ironwood tree sigil on gree...
      type: 'model', modelPath: P('banner'), scale: 1.2,
      positions: [
        { x: -3, y: 0, z: -6.8 }, { x: 3, y: 0, z: -6.8 }, { x: -11.8, y: 0, z: -2 },
        { x: -11.8, y: 0, z: 2 }, { x: 11.8, y: 0, z: -2 }, { x: 11.8, y: 0, z: 2 },
      ],
    },
    { // Woven tapestries depicting Forrester history — scenes of ...
      type: 'model', modelPath: P('tapestry'), scale: 1,
      positions: [
        { x: -11.8, y: 0, z: 0 }, { x: 11.8, y: 0, z: 0 },
      ],
    },
    { // Stark dire wolf shields mounted above the hearth arches —...
      type: 'model', modelPath: P('dire-wolf-shield'), scale: 1.2,
      positions: [
        { x: -4.5, y: 5.5, z: -6.9 }, { x: 4.5, y: 5.5, z: -6.9 },
      ],
    },
    { // Trophy antlers from the Wolfswood — hunting trophies disp...
      type: 'model', modelPath: P('mounted-antlers'), scale: 0.8,
      positions: [
        { x: 11.8, y: 5, z: -4 }, { x: 11.8, y: 5.5, z: 0 }, { x: 11.8, y: 5, z: 4 },
      ],
    },
    { type: 'model', modelPath: P('heraldic-crest'), positions: [{ x: 0, y: 5.5, z: -6.85 }], scale: 1.5 }, // Forrester ironwood tree crest above the hearth mantel — t...
    // ─── FLOOR COVERING ─────────────────────────────────────────
    { // Dried reeds and rushes scattered across the stone floor —...
      type: 'model', modelPath: P('rushes'), scale: 1,
      positions: [
        { x: -3, y: 0.01, z: -2 },
        { x: 4, y: 0.01, z: -1 },
        { x: -6, y: 0.01, z: 2 },
        { x: 7, y: 0.01, z: 3 },
        { x: -2, y: 0.01, z: 4 },
        { x: 3, y: 0.01, z: 5 },
        { x: 1, y: 0.01, z: -3 },
        { x: -4, y: 0.01, z: 1 },
        { x: 6, y: 0.01, z: -2 },
        { x: -7, y: 0.01, z: -4 },
      ],
    },
    { // Bear and wolf pelts — one on the dais beneath the throne ...
      type: 'model', modelPath: P('fur-rug'), scale: 1.5,
      positions: [
        { x: 0, y: 0.32, z: -5 }, { x: 0, y: 0.01, z: -3.5 },
      ],
    },
    { type: 'model', modelPath: P('hound-sleeping'), positions: [{ x: 2, y: 0, z: -4 }], scale: 0.8 }, // A sleeping deerhound near the hearth — Northern lords kee...
    // ─── TABLEWARE & FUNCTIONAL ─────────────────────────────────
    { // Drinking vessels set along the feasting table — Northerne...
      type: 'model', modelPath: P('goblet'), scale: 0.7,
      positions: [
        { x: -1.2, y: 0.85, z: -1.2 }, { x: 1, y: 0.85, z: -1 }, { x: -0.8, y: 0.85, z: 0.3 },
        { x: 1.3, y: 0.85, z: 0.5 }, { x: -1.5, y: 0.85, z: 1 }, { x: 0.7, y: 0.85, z: 1.3 },
        { x: -0.3, y: 0.85, z: -0.5 }, { x: 0.2, y: 0.85, z: 0.8 },
      ],
    },
    { // Ceramic plates set for the evening meal — each place gets...
      type: 'model', modelPath: P('plate'), scale: 0.7,
      positions: [
        { x: -1.5, y: 0.85, z: -1.5 }, { x: 1.5, y: 0.85, z: -1.3 }, { x: -1, y: 0.85, z: -0.2 },
        { x: 1, y: 0.85, z: 0 }, { x: -1.3, y: 0.85, z: 0.8 }, { x: 1.2, y: 0.85, z: 1 },
        { x: -0.5, y: 0.85, z: 1.5 }, { x: 0.5, y: 0.85, z: -0.8 },
      ],
    },
    { // Serving platters down the center of the table — communal ...
      type: 'model', modelPath: P('food-platter'), scale: 0.8,
      positions: [
        { x: 0, y: 0.85, z: -1 }, { x: 0, y: 0.85, z: 0.5 }, { x: 0, y: 0.85, z: -0.2 },
        { x: 0, y: 0.85, z: 1.2 },
      ],
    },
    { // Table candelabras spaced along the feasting table — suppl...
      type: 'model', modelPath: P('candelabra'), scale: 0.6,
      positions: [
        { x: 0, y: 0.85, z: -1.5 }, { x: 0, y: 0.85, z: 0 }, { x: 0, y: 0.85, z: 1.5 },
      ],
    },
    { // Ceramic wine jugs on the sideboards — servants refill gob...
      type: 'model', modelPath: P('wine-jug'), scale: 0.7,
      positions: [
        { x: -9.8, y: 0.88, z: -5 }, { x: -10.2, y: 0.88, z: -4.8 }, { x: 10, y: 0.88, z: -5 },
      ],
    },
    { // Half-burned candle stubs on sideboards and windowsill — e...
      type: 'model', modelPath: P('candle-stub'), scale: 0.5,
      positions: [
        { x: -10.3, y: 0.88, z: -5.2 }, { x: 10.2, y: 0.88, z: -4.7 }, { x: 11.6, y: 4, z: -2 },
        { x: -9.5, y: 0.88, z: -4.6 }, { x: 9.8, y: 0.88, z: -5.3 },
      ],
    },
    // ─── SURFACE DETAIL ─────────────────────────────────────────
    { // Scorch marks on the stone floor and wall from generations...
      type: 'model', modelPath: P('hearth-scorch'), scale: 1.2,
      positions: [
        { x: 0, y: 0.005, z: -5.3 }, { x: 0, y: 5, z: -6.95 },
      ],
    },
    { // Cracks in the stone floor at high-traffic areas — centuri...
      type: 'model', modelPath: P('floor-crack'), scale: 1,
      positions: [
        { x: -1, y: 0.005, z: -4.5 }, { x: -10, y: 0.005, z: 0 }, { x: 3, y: 0.005, z: 3 },
      ],
    },
    { // Damp moss in corners where moisture seeps through the sto...
      type: 'model', modelPath: P('wall-moss'), scale: 0.8,
      positions: [
        { x: -11.7, y: 0.5, z: -6 }, { x: 11.7, y: 0.5, z: -6 }, { x: -11.7, y: 0.3, z: 6 },
      ],
    },
    { type: 'model', modelPath: P('table-stain'), positions: [{ x: -0.5, y: 0.86, z: 0.3 }], scale: 0.6 }, // Ring stains and spilled ale marks on the feasting table —...
    { // Worn stone paths in the side aisles — polished smooth by ...
      type: 'model', modelPath: P('worn-path'), scale: 1,
      positions: [
        { x: -5, y: 0.003, z: 0 }, { x: 5, y: 0.003, z: 0 },
      ],
    },
    { // Cobwebs in the upper corners — the hall is old and the ce...
      type: 'model', modelPath: P('cobweb'), scale: 0.6,
      positions: [
        { x: -11.7, y: 9.5, z: -6.8 }, { x: 11.7, y: 9.5, z: -6.8 }, { x: -11.7, y: 9.5, z: 6.8 },
        { x: 11.7, y: 9.5, z: 6.8 },
      ],
    },
    { // Spilled ale on the stone floor near the feasting table — ...
      type: 'model', modelPath: P('ale-puddle'), scale: 0.5,
      positions: [
        { x: -2, y: 0.005, z: 1.5 }, { x: 3.5, y: 0.005, z: -0.5 },
      ],
    },
    { // Gnawed bones tossed to the floor — the hound's dinner scr...
      type: 'model', modelPath: P('bone-scrap'), scale: 0.4,
      positions: [
        { x: 1.5, y: 0.005, z: -3.5 }, { x: -3, y: 0.005, z: 3 },
      ],
    },
    { // Solidified wax drippings pooled on the table and floor be...
      type: 'model', modelPath: P('wax-drip'), scale: 0.3,
      positions: [
        { x: 0.2, y: 0.005, z: -3 }, { x: -0.1, y: 0.005, z: 0.2 }, { x: 0.3, y: 0.005, z: 3.2 },
      ],
    },
  ],

  postProcessOverrides: {
    bloom: { intensity: 0.7, luminanceThreshold: 0.75 },
    tiltShift: { focusArea: 0.28, feather: 0.18 },
    vignette: { darkness: 0.42 },
    colorGrading: { hue: 0.04, saturation: 0.12, brightness: 0, contrast: 0.1 },
    ssao: { aoRadius: 4.5, intensity: 2.8, distanceFalloff: 1 },
  },

  godRays: { color: 0xB0C4DE, density: 0.008, maxDensity: 0.5 },

};

export default greatHall;
