import { RoomId } from '../../../ecs/components/singletons.js';
import type { RoomData } from '../types.js';

/** Shorthand for ironrath prop model path */
const P = (name: string) => `assets/models/props/ironrath/${name}.glb`;

/**
 * Ironrath Castle — Great Hall
 *
 * Generated by Room Needs Engine.
 * 256 prop instances, 11 lights, 14 particle emitters.
 */
const greatHall: RoomData = {
  id: RoomId.IronrathGreatHall,
  name: 'Great Hall',
  dimensions: { width: 24, depth: 14, height: 10 },
  mood: 'grand',

  floorTexture: { basePath: 'assets/textures/stone/northern-floor' },
  wallTexture: { basePath: 'assets/textures/stone/northern-wall' },
  ceilingTexture: { basePath: 'assets/textures/wood/ironwood-ceiling' },

  floorColor: 0x5A5550,
  wallColor: 0x6A6560,
  ceilingColor: 0x3a2a1a,

  ambientLight: { color: 0x887766, intensity: 0.85 },

  lights: [
    { type: 'directional', position: { x: 10, y: 8, z: -2 }, color: 0x8899CC, intensity: 2.5, castShadow: true },
    { type: 'point', position: { x: 0, y: 3, z: -6.5 }, color: 0xFF5522, intensity: 12, distance: 18, decay: 1, flicker: true },
    { type: 'point', position: { x: -3, y: 8.5, z: -3 }, color: 0xFFBB55, intensity: 6, distance: 16, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: 0, y: 8.5, z: 0 }, color: 0xFFBB55, intensity: 6, distance: 16, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: 3, y: 8.5, z: 3 }, color: 0xFFBB55, intensity: 6, distance: 16, decay: 1, flicker: true }, // iron-chandelier
    { type: 'point', position: { x: -11.8, y: 4, z: -4 }, color: 0xFFAA44, intensity: 4, distance: 14, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: -11.8, y: 4, z: 3 }, color: 0xFFAA44, intensity: 4, distance: 14, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: 11.8, y: 4, z: -4 }, color: 0xFFAA44, intensity: 4, distance: 14, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: 11.8, y: 4, z: 3 }, color: 0xFFAA44, intensity: 4, distance: 14, decay: 1, flicker: true }, // wall-sconce
    { type: 'point', position: { x: -4, y: 0, z: -5 }, color: 0xFF6B35, intensity: 6, distance: 14, decay: 1, flicker: true }, // iron-brazier
    { type: 'point', position: { x: 4, y: 0, z: -5 }, color: 0xFF6B35, intensity: 6, distance: 14, decay: 1, flicker: true }, // iron-brazier
  ],

  doors: [
    {
      position: { x: -12, y: 0, z: 0 },
      halfExtents: { x: 0.8, z: 1.5 },
      targetRoomId: RoomId.IronrathGreatHall, // placeholder — update with actual target
      spawnPoint: { x: 0, y: 0, z: 0 },
      wall: 'west',
    },
  ],

  npcs: [
    { label: 'Lord Forrester', spriteColor: '#2d2318', spritePath: 'assets/sprites/npcs/forrester-lord.png', position: { x: 0, y: 0.3, z: -5.8 } },
    { label: 'Lady Forrester', spriteColor: '#2d5a27', spritePath: 'assets/sprites/npcs/forrester-lady.png', position: { x: -2.5, y: 0.3, z: -5.5 } },
    { label: 'Guard (door)', spriteColor: '#3c3228', spritePath: 'assets/sprites/npcs/forrester-guard.png', position: { x: -10, y: 0, z: 0 } },
    { label: 'Guard (dais)', spriteColor: '#3c3228', spritePath: 'assets/sprites/npcs/forrester-guard.png', position: { x: 4, y: 0, z: -4.5 } },
    { label: 'Servant (table)', spriteColor: '#6e5f4b', spritePath: 'assets/sprites/npcs/forrester-servant.png', position: { x: -3, y: 0, z: 1 } },
    { label: 'Servant (hearth)', spriteColor: '#6e5f4b', spritePath: 'assets/sprites/npcs/forrester-servant.png', position: { x: 1.5, y: 0, z: -6 } },
    { label: 'Maester', spriteColor: '#5f5c58', spritePath: 'assets/sprites/npcs/forrester-maester.png', position: { x: 2.5, y: 0.3, z: -5.5 } },
  ],

  particles: [
    { type: 'dust', region: { minX: -10, maxX: 10, minY: 1, maxY: 8, minZ: -6, maxZ: 5 }, count: 100 },
    { type: 'embers', position: { x: 0, y: 3, z: -6.5 }, count: 30 },
    { type: 'smoke', position: { x: 0, y: 4, z: -6.5 }, count: 25 },
    { type: 'embers', position: { x: -3, y: 8.5, z: -3 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: 0, y: 8.5, z: 0 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: 3, y: 8.5, z: 3 }, count: 10 }, // iron-chandelier
    { type: 'embers', position: { x: -11.8, y: 4, z: -4 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: -11.8, y: 4, z: 3 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: 11.8, y: 4, z: -4 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: 11.8, y: 4, z: 3 }, count: 8 }, // wall-sconce
    { type: 'embers', position: { x: -4, y: 0, z: -5 }, count: 12 }, // iron-brazier
    { type: 'embers', position: { x: 4, y: 0, z: -5 }, count: 12 }, // iron-brazier
    { type: 'dust-in-light', region: { minX: 2, maxX: 10, minY: 2, maxY: 8, minZ: -5, maxZ: 1 }, count: 40, lightDirection: { x: -0.7, y: -0.5, z: 0.5 } },
    { type: 'dust', region: { minX: -3, maxX: 3, minY: 1, maxY: 7, minZ: -7, maxZ: -4 }, count: 15, driftDirection: { x: 0, y: -0.3, z: 0 } },
  ],

  props: [
    // ─── STRUCTURAL ─────────────────────────────────────────────
    { // Ironwood pillars flanking the central hall — Forrester si...
      type: 'model', modelPath: P('ironwood-column'), scale: 1,
      positions: [
        { x: -5, y: 0, z: -4 }, { x: -5, y: 0, z: 0 }, { x: -5, y: 0, z: 4 },
        { x: 5, y: 0, z: -4 }, { x: 5, y: 0, z: 0 }, { x: 5, y: 0, z: 4 },
        { x: -8, y: 0, z: 5.5 }, { x: 8, y: 0, z: 5.5 },
      ],
    },
    { type: 'model', modelPath: P('stone-hearth'), positions: [{ x: 0, y: 0.005, z: -6.8 }], scale: 1.2 }, // Great stone hearth dominating the north wall
    { type: 'model', modelPath: P('raised-dais'), positions: [{ x: 0, y: 0.005, z: -5.5 }], scale: 1 }, // Stone platform elevating the lord's seat
    { // Load-bearing stone arches flanking the hearth and framing...
      type: 'model', modelPath: P('stone-arch'), scale: 1,
      positions: [
        { x: -4.5, y: 0, z: -6.9 }, { x: 4.5, y: 0, z: -6.9 }, { x: 0, y: 0, z: 6.9, rotationY: 3.142 },
      ],
    },
    { // Wall-engaged half-columns articulating the east and west ...
      type: 'model', modelPath: P('stone-pilaster'), scale: 1,
      positions: [
        { x: -11.9, y: 0, z: -5 }, { x: -11.9, y: 0, z: -1 }, { x: -11.9, y: 0, z: 3 },
        { x: 11.9, y: 0, z: -5, rotationY: 3.142 }, { x: 11.9, y: 0, z: -1, rotationY: 3.142 }, { x: 11.9, y: 0, z: 3, rotationY: 3.142 },
      ],
    },
    { // Stone corbels supporting roof beams at wall junctions
      type: 'model', modelPath: P('corbel-bracket'), scale: 0.8,
      positions: [
        { x: -11.8, y: 8.5, z: -4 }, { x: -11.8, y: 8.5, z: 0 }, { x: -11.8, y: 8.5, z: 4 },
        { x: 11.8, y: 8.5, z: -4 }, { x: 11.8, y: 8.5, z: 0 }, { x: 11.8, y: 8.5, z: 4 },
      ],
    },
    { type: 'model', modelPath: P('stone-window-frame'), positions: [{ x: 11.9, y: 3, z: -2, rotationY: -1.571 }], scale: 1 }, // Narrow window slit with stone surround on east wall
    { type: 'model', modelPath: P('door-frame'), positions: [{ x: -11.9, y: 0, z: 0, rotationY: 1.571 }], scale: 1 }, // Heavy stone door frame on the west wall
    { // Main ironwood roof beams spanning the full hall width
      type: 'model', modelPath: P('roof-beam'), scale: 1,
      positions: [
        { x: 0, y: 9.2, z: -4 }, { x: 0, y: 9.2, z: 0 }, { x: 0, y: 9.2, z: 4 },
      ],
    },
    { // Cross joists spanning between main beams
      type: 'model', modelPath: P('roof-joist'), scale: 1,
      positions: [
        { x: -4, y: 9.5, z: -2, rotationY: 1.571 }, { x: 4, y: 9.5, z: -2, rotationY: 1.571 }, { x: -4, y: 9.5, z: 2, rotationY: 1.571 },
        { x: 4, y: 9.5, z: 2, rotationY: 1.571 },
      ],
    },
    { // Visible rafter sets at north and south ends
      type: 'model', modelPath: P('rafter-set'), scale: 0.8,
      positions: [
        { x: 0, y: 9, z: -6 }, { x: 0, y: 9, z: 6 },
      ],
    },
    // ─── FURNITURE ──────────────────────────────────────────────
    { type: 'model', modelPath: P('ironwood-throne'), positions: [{ x: 0, y: 0.3, z: -5.8 }], scale: 1 }, // The lord's ironwood throne — carved from a single trunk
    { // High seats flanking the throne
      type: 'model', modelPath: P('high-seat'), scale: 0.9,
      positions: [
        { x: -2.5, y: 0.3, z: -5.5, rotationY: 0.15 },
        { x: 2.5, y: 0.3, z: -5.5, rotationY: -0.15 },
      ],
    },
    { type: 'model', modelPath: P('long-table'), positions: [{ x: 0, y: 0.005, z: 0 }], scale: 1 }, // Great feasting table — center of social life
    { // Ironwood benches flanking the feasting table
      type: 'model', modelPath: P('bench'), scale: 1,
      positions: [
        { x: -2.5, y: 0, z: -1.5 }, { x: -2.5, y: 0, z: 0 }, { x: -2.5, y: 0, z: 1.5 },
        { x: 2.5, y: 0, z: -1.5, rotationY: 3.142 }, { x: 2.5, y: 0, z: 0, rotationY: 3.142 }, { x: 2.5, y: 0, z: 1.5, rotationY: 3.142 },
      ],
    },
    { // Chairs at the table ends
      type: 'model', modelPath: P('chair'), scale: 0.9,
      positions: [
        { x: 0, y: 0, z: -2.5, rotationY: 3.142 }, { x: 0, y: 0, z: 2.5 },
      ],
    },
    { // Serving tables near the dais — where servants stage food ...
      type: 'model', modelPath: P('sideboard'), scale: 0.9,
      positions: [
        { x: -10, y: 0, z: -5 }, { x: 10, y: 0, z: -5, rotationY: 3.142 },
      ],
    },
    { // Stools at specific positions — overflow seating
      type: 'model', modelPath: P('stool'), scale: 0.8,
      positions: [
        { x: -9, y: 0, z: -3 },
        { x: 9, y: 0, z: -3 },
        { x: -8, y: 0, z: 2 },
        { x: 8, y: 0, z: 2 },
        { x: -7, y: 0, z: 4, rotationY: 0.3 },
        { x: 7, y: 0, z: 4, rotationY: -0.2 },
        { x: -6, y: 0, z: -2, rotationY: 0.5 },
        { x: 6, y: 0, z: 3, rotationY: -0.4 },
        { x: -3, y: 0, z: 4, rotationY: 1.2 },
        { x: 3, y: 0, z: 5, rotationY: -0.8 },
      ],
    },
    { // Weapon racks near the south wall
      type: 'model', modelPath: P('weapon-rack'), scale: 0.9,
      positions: [
        { x: -11.5, y: 0, z: 5 }, { x: 11.5, y: 0, z: 5 },
      ],
    },
    { // Iron-bound storage chests — household goods
      type: 'model', modelPath: P('wooden-chest'), scale: 0.9,
      positions: [
        { x: 9, y: 0, z: -5, rotationY: -0.3 }, { x: 10, y: 0, z: 6, rotationY: 0.5 }, { x: -10.5, y: 0, z: 6, rotationY: -0.4 },
        { x: -9, y: 0, z: 4, rotationY: 0.2 },
      ],
    },
    { // Bookshelves near the south wall — records and accounts
      type: 'model', modelPath: P('bookshelf'), scale: 0.9,
      positions: [
        { x: -10, y: 0, z: 6.5 }, { x: -8, y: 0, z: 6.5 }, { x: 10, y: 0, z: 6.5, rotationY: 3.142 },
        { x: 8, y: 0, z: 6.5, rotationY: 3.142 },
      ],
    },
    { // Ale and wine barrels along walls — drink stores for feasts
      type: 'model', modelPath: P('barrel'), scale: 0.7,
      positions: [
        { x: -11.3, y: 0, z: -3, rotationY: 0.4 }, { x: -11.3, y: 0, z: -4, rotationY: -0.2 }, { x: 11.3, y: 0, z: 2, rotationY: 0.8 },
        { x: 11.3, y: 0, z: 3, rotationY: -0.5 }, { x: -9, y: 0, z: 6.3, rotationY: 0.1 }, { x: 9, y: 0, z: 6.3, rotationY: -0.3 },
      ],
    },
    { // Supply crates stacked near walls — provisions and househo...
      type: 'model', modelPath: P('crate'), scale: 0.6,
      positions: [
        { x: -11.2, y: 0, z: -2.5, rotationY: 0.3 },
        { x: -11.2, y: 0.5, z: -2.8, rotationY: 0.8 },
        { x: 11.2, y: 0, z: 1.5, rotationY: -0.2 },
        { x: -7, y: 0, z: 6.3, rotationY: 0.6 },
      ],
    },
    { // Armor display stands along the aisles
      type: 'model', modelPath: P('armor-stand'), scale: 0.9,
      positions: [
        { x: -6, y: 0, z: -6.5 }, { x: 6, y: 0, z: -6.5, rotationY: 3.142 }, { x: -11, y: 0, z: 5.5, rotationY: 1.571 },
        { x: 11, y: 0, z: 5.5, rotationY: -1.571 },
      ],
    },
    // ─── LIGHTING FIXTURES ──────────────────────────────────────
    { // Three iron chandeliers along the central axis
      type: 'model', modelPath: P('iron-chandelier'), scale: 1,
      positions: [
        { x: -3, y: 8.5, z: -3 }, { x: 0, y: 8.5, z: 0 }, { x: 3, y: 8.5, z: 3 },
      ],
    },
    { // Iron wall sconces — primary wall lighting
      type: 'model', modelPath: P('wall-sconce'), scale: 0.5,
      positions: [
        { x: -11.8, y: 4, z: -4 }, { x: -11.8, y: 4, z: 3 }, { x: 11.8, y: 4, z: -4 },
        { x: 11.8, y: 4, z: 3 },
      ],
    },
    { // Iron torch holder brackets mounted below wall sconces
      type: 'model', modelPath: P('iron-torch-holder'), scale: 0.6,
      positions: [
        { x: -11.8, y: 3.8, z: -4 }, { x: -11.8, y: 3.8, z: 3 }, { x: 11.8, y: 3.8, z: -4, rotationY: 3.142 },
        { x: 11.8, y: 3.8, z: 3, rotationY: 3.142 },
      ],
    },
    { // Standing iron braziers flanking the dais
      type: 'model', modelPath: P('iron-brazier'), scale: 0.9,
      positions: [
        { x: -4, y: 0, z: -5 }, { x: 4, y: 0, z: -5 },
      ],
    },
    { // Iron candle trees flanking the throne
      type: 'model', modelPath: P('iron-candle-tree'), scale: 0.8,
      positions: [
        { x: -1.2, y: 0.3, z: -5.8 }, { x: 1.2, y: 0.3, z: -5.8 },
      ],
    },
    { // Wall torches along the east wall — additional lighting fo...
      type: 'model', modelPath: P('torch-wall'), scale: 0.5,
      positions: [
        { x: 12, y: 3.5, z: -5, rotationY: -1.571 },
        { x: 12, y: 3.5, z: -3, rotationY: -1.571 },
        { x: 12, y: 3.5, z: -1, rotationY: -1.571 },
        { x: 12, y: 3.5, z: 1, rotationY: -1.571 },
        { x: 12, y: 3.5, z: 3, rotationY: -1.571 },
        { x: 12, y: 3.5, z: 5, rotationY: -1.571 },
        { x: -12, y: 3.5, z: -5, rotationY: 1.571 },
        { x: -12, y: 3.5, z: -3, rotationY: 1.571 },
        { x: -12, y: 3.5, z: 3, rotationY: 1.571 },
        { x: -12, y: 3.5, z: 5, rotationY: 1.571 },
      ],
    },
    { // Iron sconces along the north wall
      type: 'model', modelPath: P('sconce-iron'), scale: 0.5,
      positions: [
        { x: -8, y: 3.5, z: -7 },
        { x: -4, y: 3.5, z: -7 },
        { x: 0, y: 3.5, z: -7 },
        { x: 4, y: 3.5, z: -7 },
        { x: 8, y: 3.5, z: -7 },
        { x: -8, y: 3.5, z: 7, rotationY: 3.142 },
        { x: -4, y: 3.5, z: 7, rotationY: 3.142 },
        { x: 0, y: 3.5, z: 7, rotationY: 3.142 },
        { x: 4, y: 3.5, z: 7, rotationY: 3.142 },
        { x: 8, y: 3.5, z: 7, rotationY: 3.142 },
      ],
    },
    { // Iron lanterns on the floor near columns and walls — suppl...
      type: 'model', modelPath: P('lantern'), scale: 0.5,
      positions: [
        { x: -5.2, y: 0, z: -4.2 }, { x: 5.2, y: 0, z: -4.2 }, { x: -5.2, y: 0, z: 0.2 },
        { x: 5.2, y: 0, z: 0.2 }, { x: -5.2, y: 0, z: 4.2 }, { x: 5.2, y: 0, z: 4.2 },
        { x: -8.2, y: 0, z: 5.7 }, { x: 8.2, y: 0, z: 5.7 },
      ],
    },
    // ─── WALL DECOR ─────────────────────────────────────────────
    { // Forrester house banners — ironwood tree sigil on green field
      type: 'model', modelPath: P('banner'), scale: 1.2,
      positions: [
        { x: -3, y: 3.5, z: -6.8 }, { x: 3, y: 3.5, z: -6.8 }, { x: -8, y: 3.5, z: -6.8 },
        { x: 8, y: 3.5, z: -6.8 }, { x: -11.8, y: 3.5, z: -2 }, { x: -11.8, y: 3.5, z: 2 },
        { x: 11.8, y: 3.5, z: -2 }, { x: 11.8, y: 3.5, z: 2 },
      ],
    },
    { // Woven tapestries depicting Forrester history
      type: 'model', modelPath: P('tapestry'), scale: 1,
      positions: [
        { x: -11.8, y: 3, z: -4 }, { x: 11.8, y: 3, z: -4 }, { x: -11.8, y: 3, z: 4 },
        { x: 11.8, y: 3, z: 4 },
      ],
    },
    { // Stark dire wolf shields mounted above hearth arches
      type: 'model', modelPath: P('dire-wolf-shield'), scale: 1.2,
      positions: [
        { x: -4.5, y: 5.5, z: -6.9 }, { x: 4.5, y: 5.5, z: -6.9 },
      ],
    },
    { // Trophy antlers from the Wolfswood on the east wall
      type: 'model', modelPath: P('mounted-antlers'), scale: 0.8,
      positions: [
        { x: 11.8, y: 5, z: -4 }, { x: 11.8, y: 5.5, z: 0 }, { x: 11.8, y: 5, z: 4 },
      ],
    },
    { type: 'model', modelPath: P('heraldic-crest'), positions: [{ x: 0, y: 5.5, z: -6.85 }], scale: 1.5 }, // Forrester ironwood tree crest above the hearth mantel
    // ─── FLOOR COVERING ─────────────────────────────────────────
    { // Dried rushes covering the stone floor — universal medieva...
      type: 'model', modelPath: P('rushes'), scale: 1,
      positions: [
        { x: -3, y: 0.005, z: -3 },
        { x: 0, y: 0.005, z: -3 },
        { x: 3, y: 0.005, z: -3 },
        { x: -3, y: 0.005, z: 0 },
        { x: 0, y: 0.005, z: 0 },
        { x: 3, y: 0.005, z: 0 },
        { x: -3, y: 0.005, z: 3 },
        { x: 0, y: 0.005, z: 3 },
        { x: 3, y: 0.005, z: 3 },
        { x: -6, y: 0.005, z: -5 },
        { x: 6, y: 0.005, z: -5 },
        { x: -6, y: 0.005, z: 0 },
        { x: 6, y: 0.005, z: 0 },
        { x: -6, y: 0.005, z: 4 },
        { x: 6, y: 0.005, z: 4 },
        { x: -9, y: 0.005, z: -3 },
        { x: 9, y: 0.005, z: -3 },
        { x: -9, y: 0.005, z: 2 },
        { x: 9, y: 0.005, z: 2 },
        { x: 0, y: 0.005, z: 5 },
      ],
    },
    { // Bear and wolf pelts — one on the dais, one for supplicants
      type: 'model', modelPath: P('fur-rug'), scale: 1.5,
      positions: [
        { x: 0, y: 0.32, z: -5 }, { x: 0, y: 0.01, z: -3.5 },
      ],
    },
    { type: 'model', modelPath: P('hound-sleeping'), positions: [{ x: 2, y: 0, z: -4 }], scale: 0.8 }, // A sleeping deerhound near the hearth
    // ─── TABLEWARE & FUNCTIONAL ─────────────────────────────────
    { // Drinking vessels set along the feasting table
      type: 'model', modelPath: P('goblet'), scale: 0.7,
      positions: [
        { x: -1.8, y: 1.07, z: -0.4 },
        { x: 1.5, y: 1.07, z: -0.3 },
        { x: -0.8, y: 1.07, z: 0.2 },
        { x: 2.2, y: 1.07, z: 0.35 },
        { x: -2, y: 1.07, z: 0.1 },
        { x: 0.5, y: 1.07, z: -0.45 },
        { x: -10.1, y: 0.88, z: -5.3 },
        { x: -9.7, y: 0.88, z: -4.5 },
        { x: 10.1, y: 0.88, z: -4.9 },
        { x: 9.7, y: 0.88, z: -5.4 },
        { x: -3, y: 0.005, z: -0.5, rotationY: 1.2 },
        { x: 2.5, y: 0.005, z: 1, rotationY: 2.8 },
        { x: -1, y: 0.005, z: 2, rotationY: 0.6 },
      ],
    },
    { // Ceramic plates set for the evening meal
      type: 'model', modelPath: P('plate'), scale: 0.7,
      positions: [
        { x: -1.5, y: 1.07, z: -0.35 }, { x: 1.2, y: 1.07, z: -0.4 }, { x: -0.5, y: 1.07, z: 0.3 },
        { x: 2, y: 1.07, z: 0.25 }, { x: -2, y: 0.005, z: 1.5, rotationY: 0.4 }, { x: 3, y: 0.005, z: -1, rotationY: 2.1 },
      ],
    },
    { // Serving platters down the table center — communal dishes
      type: 'model', modelPath: P('food-platter'), scale: 0.8,
      positions: [
        { x: -1.8, y: 1.07, z: 0 }, { x: -0.3, y: 1.07, z: 0.05 }, { x: 1, y: 1.07, z: -0.1 },
        { x: 2.3, y: 1.07, z: 0 },
      ],
    },
    { // Table candelabras along the feasting table
      type: 'model', modelPath: P('candelabra'), scale: 0.6,
      positions: [
        { x: -1.5, y: 1.07, z: 0 }, { x: 0.5, y: 1.07, z: 0 }, { x: 2, y: 1.07, z: 0 },
        { x: -10, y: 0.88, z: -4.5 }, { x: 10, y: 0.88, z: -5.5 },
      ],
    },
    { // Ceramic wine jugs on the sideboards
      type: 'model', modelPath: P('wine-jug'), scale: 0.7,
      positions: [
        { x: -9.8, y: 0.88, z: -5 }, { x: -10.2, y: 0.88, z: -4.8 }, { x: 10, y: 0.88, z: -5 },
        { x: 10.3, y: 0.88, z: -5.2 },
      ],
    },
    { // Half-burned candle stubs on sideboards and windowsill
      type: 'model', modelPath: P('candle-stub'), scale: 0.5,
      positions: [
        { x: -10.3, y: 0.88, z: -5.2 }, { x: 10.2, y: 0.88, z: -4.7 }, { x: 11.6, y: 4, z: -2 },
        { x: -9.5, y: 0.88, z: -4.6 }, { x: 9.8, y: 0.88, z: -5.3 },
      ],
    },
    { // Wooden drinking tankards on the table — cheaper than gobl...
      type: 'model', modelPath: P('tankard'), scale: 0.5,
      positions: [
        { x: -1.2, y: 1.07, z: 0.3 }, { x: 0.8, y: 1.07, z: -0.25 }, { x: 1.8, y: 1.07, z: 0.4 },
      ],
    },
    // ─── SURFACE DETAIL ─────────────────────────────────────────
    { // Scorch marks from generations of hearth fires
      type: 'model', modelPath: P('hearth-scorch'), scale: 0.8,
      positions: [
        { x: -1.5, y: 0.005, z: -6 }, { x: 1.5, y: 0.005, z: -6 }, { x: 0, y: 0.005, z: -5.5 },
        { x: -3, y: 0.005, z: -5.5 }, { x: 3, y: 0.005, z: -5.5 },
      ],
    },
    { // Cracks in the stone floor — centuries of wear
      type: 'model', modelPath: P('floor-crack'), scale: 0.8,
      positions: [
        { x: -4, y: 0.005, z: -1, rotationY: 0.3 }, { x: 2, y: 0.005, z: 2, rotationY: 1.1 }, { x: -7, y: 0.005, z: -4, rotationY: 0.7 },
        { x: 6, y: 0.005, z: 3, rotationY: 2.4 }, { x: 0, y: 0.005, z: -2, rotationY: 0.5 }, { x: -8, y: 0.005, z: 1, rotationY: 1.8 },
        { x: 8, y: 0.005, z: -2, rotationY: 0.9 },
      ],
    },
    { // Damp moss on lower walls — the North is cold and wet
      type: 'model', modelPath: P('wall-moss'), scale: 0.6,
      positions: [
        { x: -11.8, y: 0.2, z: -5.5 }, { x: -11.8, y: 0.3, z: 1 }, { x: 11.8, y: 0.2, z: -3 },
        { x: 11.8, y: 0.15, z: 5 }, { x: -5, y: 0.1, z: -6.8 }, { x: 5, y: 0.1, z: -6.8 },
        { x: -11.8, y: 0.25, z: 4.5 }, { x: 11.8, y: 0.2, z: 1 },
      ],
    },
    { // Ring stains, grease marks, and spilled ale on the feastin...
      type: 'model', modelPath: P('table-stain'), scale: 0.5,
      positions: [
        { x: -0.5, y: 1.065, z: -0.2 }, { x: 0.8, y: 1.065, z: 0.15 }, { x: -1.5, y: 1.065, z: 0.3 },
        { x: 1.5, y: 1.065, z: -0.1 },
      ],
    },
    { // Worn stone paths polished smooth by generations of traffic
      type: 'model', modelPath: P('worn-path'), scale: 1,
      positions: [
        { x: 0, y: 0.003, z: 3 }, { x: 0, y: 0.003, z: -2 },
      ],
    },
    { // Cobwebs in upper corners and between rafters
      type: 'model', modelPath: P('cobweb'), scale: 0.6,
      positions: [
        { x: -11.7, y: 9.5, z: -6.8 }, { x: 11.7, y: 9.5, z: -6.8 }, { x: -11.7, y: 9.5, z: 6.8 },
        { x: 11.7, y: 9.5, z: 6.8 }, { x: -11.7, y: 9.5, z: 0 }, { x: 11.7, y: 9.5, z: 0 },
        { x: 0, y: 9.5, z: -6.8 }, { x: 0, y: 9.5, z: 6.8 },
      ],
    },
    { // Spilled ale puddles on the stone floor — evidence of feas...
      type: 'model', modelPath: P('ale-puddle'), scale: 0.5,
      positions: [
        { x: -1, y: 0.004, z: 0.5, rotationY: 0.8 }, { x: 2, y: 0.004, z: -1, rotationY: 2.3 }, { x: -4, y: 0.004, z: 2, rotationY: 1.5 },
      ],
    },
    { // Gnawed bones tossed to the floor — hound dinner scraps
      type: 'model', modelPath: P('bone-scrap'), scale: 0.4,
      positions: [
        { x: 1.5, y: 0.005, z: -3.5, rotationY: 0.6 },
        { x: -2, y: 0.005, z: -4, rotationY: 2.1 },
        { x: 3, y: 0.005, z: 1, rotationY: 1.2 },
        { x: -1, y: 0.005, z: 3, rotationY: 0.9 },
      ],
    },
    { // Solidified wax drippings beneath chandeliers and sconces
      type: 'model', modelPath: P('wax-drip'), scale: 0.3,
      positions: [
        { x: 0, y: 0.005, z: -3, rotationY: 0.5 },
        { x: 0, y: 0.005, z: 0, rotationY: 1.8 },
        { x: 0, y: 0.005, z: 3, rotationY: 2.9 },
        { x: -11.5, y: 0.005, z: -4, rotationY: 0.3 },
        { x: 11.5, y: 0.005, z: -4, rotationY: 1.7 },
        { x: -11.5, y: 0.005, z: 3, rotationY: 0.8 },
        { x: 11.5, y: 0.005, z: 3, rotationY: 2.2 },
      ],
    },
  ],

  parallaxBackground: [
    { texturePath: 'assets/backgrounds/ironrath/layer-sky.png', depth: 20, scrollFactor: 0, height: 10, yOffset: 6 },
    { texturePath: 'assets/backgrounds/ironrath/layer-mountains.png', depth: 15, scrollFactor: 0.1, height: 10, yOffset: 5 },
    { texturePath: 'assets/backgrounds/ironrath/layer-canopy.png', depth: 10, scrollFactor: 0.2, height: 10, yOffset: 4 },
    { texturePath: 'assets/backgrounds/ironrath/layer-trees.png', depth: 5, scrollFactor: 0.3, height: 10, yOffset: 3 },
  ],

  postProcessOverrides: {
    bloom: { intensity: 0.7, luminanceThreshold: 0.85 },
    tiltShift: { focusArea: 0.42, feather: 0.28 },
    vignette: { darkness: 0.42 },
    colorGrading: { hue: 0.04, saturation: 0.12, brightness: 0, contrast: 0.1 },
    ssao: { aoRadius: 4.5, intensity: 2.8, distanceFalloff: 1 },
  },

  godRays: { color: 0x8899CC, density: 0.008, maxDensity: 0.5 },

  textureTemplate: 'northern-grand',
};

export default greatHall;
