import { z } from 'zod';

export const RoomInputSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  dimensions: z.object({
    width: z.number().positive(),
    depth: z.number().positive(),
    height: z.number().positive(),
  }),
  culture: z.string(),
  wealth: z.enum(['poor', 'modest', 'wealthy', 'royal']),
  era: z.string(),
  lore: z.string(),
  purpose: z.string(),
  castle: z.string().default('ironrath'),
  /** Optional pre-existing features file path */
  featuresFile: z.string().optional(),
  /** Optional doors to define exclusion zones */
  doors: z.array(z.object({
    position: z.object({ x: z.number(), y: z.number(), z: z.number() }),
    halfExtents: z.object({ x: z.number(), z: z.number() }),
    wall: z.enum(['north', 'south', 'east', 'west']),
  })).optional(),
  /** Density tier controlling how many props to generate per sq meter */
  densityTier: z.enum(['sparse', 'moderate', 'dense', 'aaa-showcase']).default('moderate'),
  /** Texture engine template ID (e.g. 'northern-grand') — enables shader detail + decals */
  textureTemplate: z.string().optional(),
  /** Optional surface textures */
  floorTexture: z.string().optional(),
  wallTexture: z.string().optional(),
  ceilingTexture: z.string().optional(),
  /** Fallback colors when PBR textures aren't loaded */
  floorColor: z.string().optional(),
  wallColor: z.string().optional(),
  ceilingColor: z.string().optional(),
  /** NPCs to place in the room */
  npcs: z.array(z.object({
    label: z.string(),
    spriteColor: z.string(),
    spritePath: z.string(),
    position: z.object({ x: z.number(), y: z.number(), z: z.number() }),
  })).optional(),
  /** Parallax background layers visible through windows */
  parallaxBackground: z.array(z.object({
    texturePath: z.string(),
    depth: z.number(),
    scrollFactor: z.number(),
    height: z.number(),
    yOffset: z.number(),
  })).optional(),
  /** Extra particles not generated by the engine (dust-in-light, falling ash, etc.) */
  extraParticles: z.array(z.object({
    type: z.string(),
    region: z.object({
      minX: z.number(), maxX: z.number(),
      minY: z.number(), maxY: z.number(),
      minZ: z.number(), maxZ: z.number(),
    }).optional(),
    position: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional(),
    count: z.number(),
    lightDirection: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional(),
    driftDirection: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional(),
    spread: z.number().optional(),
  })).optional(),
});
